version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: dsi320-mysql
    restart: always
    environment:
      MYSQL_DATABASE: dsi320
      MYSQL_ROOT_PASSWORD: dsi320
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
