version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_DATABASE: quotes
      MYSQL_ROOT_PASSWORD: my-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
